### ISSUE TITLE
Linear regression fails when number of points is zero

### ISSUE THREAD

**Issue by bulenterdemir** [sinemerdemir/py#1]
I was trying to run the regression code and tested with an empty list. The program crashed. Please fix it.

**Comment by bulenterdemir** [comment]
Hi, I couldn't find the solution yet. Please help.

**Comment by sinemerdemir** [comment]
I’ll look into it and get back to you with what I find.

**Comment by sinemerdemir** [comment]
I tried to solve your problem but I'm not sure. Can you look at the PA05fixed.py file and check if it solves your problem?

**Comment by bulenterdemir** [comment]
Yes, that's terrific... You're the most helpful. It works now. Thank you...
