### ISSUE TITLE
Is there a version using libraries

### ISSUE THREAD

**Issue by bulenterdemir** [sinemerdemir/py#2]
The code implements the linear regression method from stratch. Is there a shorter and simpler version which uses python libraries?

**Comment by bulenterdemir** [comment]
Hi, any update on this one? Please help.

**Comment by sinemerdemir** [comment]
I’m not sure, but I’ll find out and let you know.

**Comment by sinemerdemir** [comment]
I'm not sure but I believe you can you can achieve linear regression using Python libraries like NumPy and Scikit-learn, which will make the code shorter and more concise.

**Comment by bulenterdemir** [comment]
That's a fantastic idea. I'll go ahead and study all those libraries. Thank you very much. 

You can close the issue completed if you fancy.
