### ISSUE TITLE
How to run the PA06 file

### ISSUE THREAD

**Issue by bulenterdemir** [sinemerdemir/py#3]
Hi, I'm reviewing the PA06 code, the one about the labyrinth problem. I load the file onto my computer and run it, however, nothing happens. Can you please help me with the issue? What am I doing wrong?

Regards,
Bulent

**Comment by sinemerdemir** [comment]
did you also download the labyrinth.dat file? You need it to run the program.

**Comment by bulenterdemir** [comment]
oh. that's it. Yes, I managed to run it after downloading the file. Thank you very much. You can close the issue completed now.
